version: '3.3'
services:
  app:
    image: 'registry.svtrobotics.local:61000/scp-app'
    container_name: 'scp-app'
    ports:
      - '60000:5001'
    environment:
      - ASPNETCORE_URLS=http://*:5000;https://*:5001
    depends_on:
      - db
      - mockaethonapi
    networks:
      - scp-app
  mockaethonapi:
    image: 'registry.svtrobotics.local:61000/aethon-mock-api'
    container_name: 'scp-app.aethon-mock-api'
    networks:
      - scp-app
  db:
    image: 'mcr.microsoft.com/mssql/server'
    container_name: 'scp-app.mssql'
    ports:
      - '60001:1433'
    environment:
      SA_PASSWORD: 'SupahAdmin1'
      ACCEPT_EULA: 'Y'
      LD_PRELOAD: /nodirect_open.so
    networks:
      - scp-app
networks:
  scp-app:
