version: '3.7'
services:
  app:
    image: 'anstle:61000/softbot-cloud-platform_app'
    ports:
      - '60000:5001'
    environment:
      - ASPNETCORE_URLS=http://*:5000;https://*:5001
    depends_on:
      - db
      - mockaethonapi
    networks:
      - lonza
  mockaethonapi:
    image: 'node:10'
    user: 'node'
    working_dir: /home/node/app
    volumes:
      - ./AethonMockApi:/home/node/app
    expose:
      - '3000'
    command: 'node index.js'
    networks:
      - lonza
  db:
    image: 'mcr.microsoft.com/mssql/server'
    expose:
      - '1433'
    environment:
      SA_PASSWORD: 'SupahAdmin1'
      ACCEPT_EULA: 'Y'
    networks:
      - lonza
networks:
  lonza:
