// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SVT.Platform.Data;

namespace SVT.Platform.Data.Migrations
{
    [DbContext(typeof(SVTContext))]
    [Migration("20190912184321_SCP-25")]
    partial class SCP25
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SVT.Platform.Data.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<DateTime>("Inserted");

                    b.Property<string>("Name");

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.AreaPool", b =>
                {
                    b.Property<int>("AreaId");

                    b.Property<int>("PoolId");

                    b.Property<int>("Id");

                    b.Property<DateTime>("Inserted");

                    b.Property<DateTime>("Updated");

                    b.HasKey("AreaId", "PoolId");

                    b.HasIndex("PoolId");

                    b.ToTable("AreaPool");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.AreaToArea", b =>
                {
                    b.Property<int>("FromAreaId");

                    b.Property<int>("ToAreaId");

                    b.Property<int?>("FromAreaId1");

                    b.Property<int>("Id");

                    b.Property<DateTime>("Inserted");

                    b.Property<DateTime>("Updated");

                    b.HasKey("FromAreaId", "ToAreaId");

                    b.HasIndex("FromAreaId1");

                    b.ToTable("AreaToArea");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.DeliveryRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AreaId");

                    b.Property<bool>("Completed");

                    b.Property<DateTime>("Inserted");

                    b.Property<string>("LonzaOrderId");

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("DeliveryRequests");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DetailsSerialized");

                    b.Property<DateTime>("Inserted");

                    b.Property<string>("Status");

                    b.Property<int>("TripRequestId");

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.HasIndex("TripRequestId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Pool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<DateTime>("Inserted");

                    b.Property<string>("Name");

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.ToTable("Pools");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AreaId");

                    b.Property<DateTime>("Cleared");

                    b.Property<string>("Description");

                    b.Property<DateTime>("Inserted");

                    b.Property<string>("Name");

                    b.Property<DateTime>("Occupied");

                    b.Property<DateTime>("Reserved");

                    b.Property<int>("TripRequestId");

                    b.Property<string>("Type");

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("TripRequestId")
                        .IsUnique();

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.TripHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Inserted");

                    b.Property<string>("Status");

                    b.Property<int>("TripRequestId");

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.HasIndex("TripRequestId");

                    b.ToTable("TripHistory");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.TripRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CartId");

                    b.Property<int>("DeliveryRequestId");

                    b.Property<DateTime>("Inserted");

                    b.Property<int>("PositionId");

                    b.Property<int?>("PreviousTripRequestId");

                    b.Property<string>("Type");

                    b.Property<DateTime>("Updated");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryRequestId");

                    b.HasIndex("PreviousTripRequestId");

                    b.ToTable("TripRequests");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.AreaPool", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.Area", "Area")
                        .WithMany("AreaPools")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SVT.Platform.Data.Models.Pool", "Pool")
                        .WithMany("AreaPools")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.AreaToArea", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.Area", "ToArea")
                        .WithMany("FromAreas")
                        .HasForeignKey("FromAreaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SVT.Platform.Data.Models.Area", "FromArea")
                        .WithMany("ToAreas")
                        .HasForeignKey("FromAreaId1");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.DeliveryRequest", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.Area", "Area")
                        .WithMany("DeliveryRequests")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Job", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.TripRequest", "TripRequest")
                        .WithMany()
                        .HasForeignKey("TripRequestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Position", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.Area", "Area")
                        .WithMany("Positions")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SVT.Platform.Data.Models.TripRequest", "TripRequest")
                        .WithOne("Position")
                        .HasForeignKey("SVT.Platform.Data.Models.Position", "TripRequestId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.TripHistory", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.TripRequest", "TripRequest")
                        .WithMany("TripHistories")
                        .HasForeignKey("TripRequestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.TripRequest", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.DeliveryRequest", "DeliveryRequest")
                        .WithMany("TripRequests")
                        .HasForeignKey("DeliveryRequestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SVT.Platform.Data.Models.TripRequest", "PreviousTripRequest")
                        .WithMany()
                        .HasForeignKey("PreviousTripRequestId");
                });
#pragma warning restore 612, 618
        }
    }
}
