// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SVT.Platform.Data;

namespace SVT.Platform.Data.Migrations
{
    [DbContext(typeof(SVTContext))]
    [Migration("20190913202821_SCP-25")]
    partial class SCP25
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SVT.Platform.Data.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AreaType")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("PoolId");

                    b.HasKey("Id");

                    b.HasIndex("AreaType");

                    b.HasIndex("PoolId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.AreaDeliveryType", b =>
                {
                    b.Property<int>("AreaId");

                    b.Property<string>("DeliveryType")
                        .HasMaxLength(50);

                    b.Property<int>("Id");

                    b.HasKey("AreaId", "DeliveryType");

                    b.HasIndex("DeliveryType");

                    b.ToTable("AreaDeliveryTypes");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.AreaMap", b =>
                {
                    b.Property<int>("DestinationAreaId");

                    b.Property<int>("SourceAreaId");

                    b.Property<int>("Id");

                    b.HasKey("DestinationAreaId", "SourceAreaId");

                    b.HasIndex("SourceAreaId");

                    b.ToTable("AreaMaps");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.AreaType", b =>
                {
                    b.Property<string>("Value")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.HasKey("Value");

                    b.ToTable("AreaTypes");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Completed");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("DeliveryType")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("DestinationAreaId");

                    b.Property<string>("InsertedBy")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<DateTime>("InsertedOn");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<int?>("OrderId");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("DeliveryStatus");

                    b.HasIndex("DeliveryType");

                    b.HasIndex("DestinationAreaId");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.DeliveryStatus", b =>
                {
                    b.Property<string>("Value")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.HasKey("Value");

                    b.ToTable("DeliveryStatuses");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.DeliveryType", b =>
                {
                    b.Property<string>("Value")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.HasKey("Value");

                    b.ToTable("DeliveryTypes");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Itinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeliveryId");

                    b.Property<string>("InsertedBy")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<DateTime>("InsertedOn");

                    b.Property<string>("ItineraryStatus")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ItineraryType")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("LocationId");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<int?>("PreviousItineraryId");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("ItineraryStatus");

                    b.HasIndex("ItineraryType");

                    b.HasIndex("LocationId");

                    b.HasIndex("PreviousItineraryId")
                        .IsUnique()
                        .HasFilter("[PreviousItineraryId] IS NOT NULL");

                    b.ToTable("Itineraries");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.ItineraryStatus", b =>
                {
                    b.Property<string>("Value")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.HasKey("Value");

                    b.ToTable("ItineraryStatuses");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.ItineraryType", b =>
                {
                    b.Property<string>("Value")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.HasKey("Value");

                    b.ToTable("ItineraryTypes");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AreaId");

                    b.Property<int?>("CartId");

                    b.Property<string>("InsertedBy")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<DateTime>("InsertedOn");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("Reserved");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("LocationType");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.LocationType", b =>
                {
                    b.Property<string>("Value")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.HasKey("Value");

                    b.ToTable("LocationTypes");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Pool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Pools");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Area", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.AreaType", "AreaTypeReference")
                        .WithMany("Areas")
                        .HasForeignKey("AreaType")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SVT.Platform.Data.Models.Pool", "Pool")
                        .WithMany("Areas")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.AreaDeliveryType", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.Area", "Area")
                        .WithMany("AreaDeliveryTypes")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SVT.Platform.Data.Models.DeliveryType", "DeliveryTypeReference")
                        .WithMany("AreaDeliveryTypes")
                        .HasForeignKey("DeliveryType")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.AreaMap", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.Area", "DestinationArea")
                        .WithMany("SourceAreas")
                        .HasForeignKey("DestinationAreaId");

                    b.HasOne("SVT.Platform.Data.Models.Area", "SourceArea")
                        .WithMany("DestinationAreas")
                        .HasForeignKey("SourceAreaId");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Delivery", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.DeliveryStatus", "DeliveryStatusReference")
                        .WithMany("Deliveries")
                        .HasForeignKey("DeliveryStatus")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SVT.Platform.Data.Models.DeliveryType", "DeliveryTypeReference")
                        .WithMany("Deliveries")
                        .HasForeignKey("DeliveryType")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SVT.Platform.Data.Models.Area", "DestinationArea")
                        .WithMany("Deliveries")
                        .HasForeignKey("DestinationAreaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Itinerary", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.Delivery", "Delivery")
                        .WithMany("Itineraries")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SVT.Platform.Data.Models.ItineraryStatus", "ItineraryStatusReference")
                        .WithMany("Itineraries")
                        .HasForeignKey("ItineraryStatus")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SVT.Platform.Data.Models.ItineraryType", "ItineraryTypeReference")
                        .WithMany("Itineraries")
                        .HasForeignKey("ItineraryType")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SVT.Platform.Data.Models.Location", "Location")
                        .WithMany("Itineraries")
                        .HasForeignKey("LocationId");

                    b.HasOne("SVT.Platform.Data.Models.Itinerary", "PreviousItinerary")
                        .WithOne("NextItinerary")
                        .HasForeignKey("SVT.Platform.Data.Models.Itinerary", "PreviousItineraryId");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Location", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.Area", "Area")
                        .WithMany("Locations")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SVT.Platform.Data.Models.LocationType", "LocationTypeReference")
                        .WithMany("Locations")
                        .HasForeignKey("LocationType")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
