// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SVT.Platform.Data;

namespace SVT.Platform.Data.Migrations
{
    [DbContext(typeof(SVTContext))]
    [Migration("20191014141751_SCP-22")]
    partial class SCP22
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SVT.Platform.Data.Models.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AreaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("PoolId")
                        .HasColumnType("int");

                    b.HasKey("AreaId");

                    b.HasIndex("AreaType");

                    b.HasIndex("PoolId");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            AreaId = 1,
                            AreaType = "fpa",
                            Name = "101B-FPA",
                            PoolId = 1
                        },
                        new
                        {
                            AreaId = 2,
                            AreaType = "cw",
                            Name = "101C-CarWash",
                            PoolId = 1
                        },
                        new
                        {
                            AreaId = 3,
                            AreaType = "stg",
                            Name = "1430-Staging",
                            PoolId = 1
                        },
                        new
                        {
                            AreaId = 4,
                            AreaType = "mal",
                            Name = "1501-MAL-A",
                            PoolId = 1
                        },
                        new
                        {
                            AreaId = 5,
                            AreaType = "mal",
                            Name = "2501-MAL-A",
                            PoolId = 1
                        },
                        new
                        {
                            AreaId = 6,
                            AreaType = "mal",
                            Name = "1501-MAL-B",
                            PoolId = 2
                        },
                        new
                        {
                            AreaId = 7,
                            AreaType = "mal",
                            Name = "2501-MAL-B",
                            PoolId = 3
                        },
                        new
                        {
                            AreaId = 8,
                            AreaType = "smal",
                            Name = "15xx-Suite MALs",
                            PoolId = 2
                        },
                        new
                        {
                            AreaId = 9,
                            AreaType = "smal",
                            Name = "25xx-Suite MALs",
                            PoolId = 3
                        });
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.AreaDeliveryType", b =>
                {
                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryType")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("AreaId", "DeliveryType");

                    b.HasIndex("DeliveryType");

                    b.ToTable("AreaDeliveryTypes");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.AreaMap", b =>
                {
                    b.Property<int>("NextAreaId")
                        .HasColumnType("int");

                    b.Property<int>("PreviousAreaId")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.HasKey("NextAreaId", "PreviousAreaId");

                    b.HasIndex("PreviousAreaId");

                    b.ToTable("AreaMaps");

                    b.HasData(
                        new
                        {
                            NextAreaId = 3,
                            PreviousAreaId = 1,
                            Active = true
                        },
                        new
                        {
                            NextAreaId = 4,
                            PreviousAreaId = 1,
                            Active = true
                        },
                        new
                        {
                            NextAreaId = 5,
                            PreviousAreaId = 1,
                            Active = true
                        },
                        new
                        {
                            NextAreaId = 3,
                            PreviousAreaId = 2,
                            Active = true
                        },
                        new
                        {
                            NextAreaId = 4,
                            PreviousAreaId = 2,
                            Active = true
                        },
                        new
                        {
                            NextAreaId = 5,
                            PreviousAreaId = 2,
                            Active = true
                        },
                        new
                        {
                            NextAreaId = 4,
                            PreviousAreaId = 3,
                            Active = true
                        },
                        new
                        {
                            NextAreaId = 5,
                            PreviousAreaId = 3,
                            Active = true
                        },
                        new
                        {
                            NextAreaId = 6,
                            PreviousAreaId = 4,
                            Active = true
                        },
                        new
                        {
                            NextAreaId = 7,
                            PreviousAreaId = 5,
                            Active = true
                        },
                        new
                        {
                            NextAreaId = 8,
                            PreviousAreaId = 6,
                            Active = true
                        },
                        new
                        {
                            NextAreaId = 9,
                            PreviousAreaId = 7,
                            Active = true
                        });
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.AreaOverflow", b =>
                {
                    b.Property<int>("DestinationAreaId")
                        .HasColumnType("int");

                    b.Property<int>("OverflowAreaId")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("DestinationAreaId", "OverflowAreaId");

                    b.HasIndex("OverflowAreaId");

                    b.ToTable("AreaOverflow");

                    b.HasData(
                        new
                        {
                            DestinationAreaId = 4,
                            OverflowAreaId = 3,
                            Active = true,
                            Priority = 1
                        },
                        new
                        {
                            DestinationAreaId = 5,
                            OverflowAreaId = 3,
                            Active = true,
                            Priority = 1
                        },
                        new
                        {
                            DestinationAreaId = 1,
                            OverflowAreaId = 3,
                            Active = true,
                            Priority = 1
                        },
                        new
                        {
                            DestinationAreaId = 2,
                            OverflowAreaId = 3,
                            Active = true,
                            Priority = 1
                        });
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.AreaType", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Value");

                    b.ToTable("AreaTypes");

                    b.HasData(
                        new
                        {
                            Value = "cw"
                        },
                        new
                        {
                            Value = "fpa"
                        },
                        new
                        {
                            Value = "mal"
                        },
                        new
                        {
                            Value = "smal"
                        },
                        new
                        {
                            Value = "stg"
                        });
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Delivery", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Canceled")
                        .HasColumnType("datetime2");

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("Completed")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("DestinationAreaId")
                        .HasColumnType("int");

                    b.Property<string>("InsertedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValueSql("suser_sname()")
                        .HasMaxLength(256);

                    b.Property<DateTime>("InsertedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValueSql("suser_sname()")
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("PreviousPrioritizedDeliveryId")
                        .HasColumnType("int");

                    b.Property<bool>("Queued")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("DeliveryId");

                    b.HasIndex("DeliveryType");

                    b.HasIndex("DestinationAreaId");

                    b.HasIndex("PreviousPrioritizedDeliveryId")
                        .IsUnique()
                        .HasFilter("[PreviousPrioritizedDeliveryId] IS NOT NULL");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.DeliveryType", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Value");

                    b.ToTable("DeliveryTypes");

                    b.HasData(
                        new
                        {
                            Value = "deliver"
                        },
                        new
                        {
                            Value = "manual"
                        },
                        new
                        {
                            Value = "return"
                        },
                        new
                        {
                            Value = "stage"
                        });
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.DevLog", b =>
                {
                    b.Property<int>("DevLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InsertedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("InsertedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Serialized")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DevLogId");

                    b.ToTable("DevLogs");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Itinerary", b =>
                {
                    b.Property<int>("ItineraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AethonRunId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Completed")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValueSql("suser_sname()")
                        .HasMaxLength(256);

                    b.Property<DateTime>("InsertedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValueSql("suser_sname()")
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("TimedOut")
                        .HasColumnType("datetime2");

                    b.HasKey("ItineraryId");

                    b.HasIndex("JobId");

                    b.HasIndex("LocationId");

                    b.ToTable("Itineraries");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AethonJobId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Canceled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Completed")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Expired")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValueSql("suser_sname()")
                        .HasMaxLength(256);

                    b.Property<DateTime>("InsertedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValueSql("suser_sname()")
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("JobId");

                    b.HasIndex("DeliveryId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("DeliveryId")
                        .HasColumnType("int");

                    b.Property<string>("InsertedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValueSql("suser_sname()")
                        .HasMaxLength(256);

                    b.Property<DateTime>("InsertedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValueSql("suser_sname()")
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("Reserved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("LocationId");

                    b.HasIndex("AreaId");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("LocationType");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            AreaId = 1,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "fpa",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "101B-FPA-001",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 2,
                            AreaId = 1,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "fpa",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "101B-FPA-002",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 3,
                            AreaId = 1,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "fpa",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "101B-FPA-003",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 4,
                            AreaId = 1,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "fpa",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "101B-FPA-004",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 5,
                            AreaId = 1,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "fpa",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "101B-FPA-005",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 6,
                            AreaId = 2,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "cw",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "101C-CW-001",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 7,
                            AreaId = 2,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "cw",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "101C-CW-002",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 8,
                            AreaId = 2,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "cw",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "101C-CW-003",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 9,
                            AreaId = 2,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "cw",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "101C-CW-004",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 10,
                            AreaId = 2,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "cw",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "101C-CW-005",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 11,
                            AreaId = 3,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "stg",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1430-STG-001",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 12,
                            AreaId = 3,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "stg",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1430-STG-002",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 13,
                            AreaId = 3,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "stg",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1430-STG-003",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 14,
                            AreaId = 3,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "stg",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1430-STG-004",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 15,
                            AreaId = 3,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "stg",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1430-STG-005",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 16,
                            AreaId = 3,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "stg",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1430-STG-006",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 17,
                            AreaId = 3,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "stg",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1430-STG-007",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 18,
                            AreaId = 3,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "stg",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1430-STG-008",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 19,
                            AreaId = 3,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "stg",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1430-STG-009",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 20,
                            AreaId = 3,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "stg",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1430-STG-010",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 21,
                            AreaId = 4,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "mal",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1501-MAL-A-001",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 22,
                            AreaId = 4,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "wait",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1501-MAL-A-WAIT-001",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 23,
                            AreaId = 4,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "wait",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1501-MAL-A-WAIT-002",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 24,
                            AreaId = 4,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "wait",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1501-MAL-A-WAIT-003",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 25,
                            AreaId = 5,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "mal",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2501-MAL-A-001",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 26,
                            AreaId = 5,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "wait",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2501-MA-A-WAIT-001",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 27,
                            AreaId = 5,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "wait",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2501-MA-A-WAIT-002",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 28,
                            AreaId = 5,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "wait",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2501-MA-A-WAIT-003",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 29,
                            AreaId = 6,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "mal",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1501-MAL-B-001",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 30,
                            AreaId = 6,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "wait",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1501-MAL-B-WAIT-001",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 31,
                            AreaId = 6,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "wait",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1501-MAL-B-WAIT-002",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 32,
                            AreaId = 6,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "wait",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1501-MAL-B-WAIT-003",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 33,
                            AreaId = 7,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "mal",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2501-MAL-B-001",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 34,
                            AreaId = 7,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "wait",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2501-MAL-B-WAIT-001",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 35,
                            AreaId = 7,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "wait",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2501-MAL-B-WAIT-002",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 36,
                            AreaId = 7,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "wait",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2501-MAL-B-WAIT-003",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 37,
                            AreaId = 8,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "smal",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1528-MAL-001",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 38,
                            AreaId = 8,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "wait",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1528-MAL-WAIT-001",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 39,
                            AreaId = 8,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "wait",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1528-MAL-WAIT-002",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 40,
                            AreaId = 8,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "wait",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1528-MAL-WAIT-003",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 41,
                            AreaId = 9,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "smal",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2519-MAL-001",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 42,
                            AreaId = 9,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "wait",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2519-MAL-WAIT-001",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 43,
                            AreaId = 9,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "wait",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2519-MAL-WAIT-002",
                            Reserved = false
                        },
                        new
                        {
                            LocationId = 44,
                            AreaId = 9,
                            InsertedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "wait",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2519-MAL-WAIT-003",
                            Reserved = false
                        });
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.LocationType", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Value");

                    b.ToTable("LocationTypes");

                    b.HasData(
                        new
                        {
                            Value = "cw"
                        },
                        new
                        {
                            Value = "fpa"
                        },
                        new
                        {
                            Value = "mal"
                        },
                        new
                        {
                            Value = "smal"
                        },
                        new
                        {
                            Value = "stg"
                        },
                        new
                        {
                            Value = "wait"
                        });
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Pool", b =>
                {
                    b.Property<int>("PoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("PoolId");

                    b.ToTable("Pools");

                    b.HasData(
                        new
                        {
                            PoolId = 1,
                            Name = "Pool 1"
                        },
                        new
                        {
                            PoolId = 2,
                            Name = "Pool 2"
                        },
                        new
                        {
                            PoolId = 3,
                            Name = "Pool 3"
                        });
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.ScheduledDelivery", b =>
                {
                    b.Property<int>("ScheduledDeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Canceled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Completed")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int");

                    b.Property<int>("DestinationLocationId")
                        .HasColumnType("int");

                    b.Property<string>("InsertedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValueSql("suser_sname()")
                        .HasMaxLength(256);

                    b.Property<DateTime>("InsertedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValueSql("suser_sname()")
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("TTL")
                        .HasColumnType("datetime2");

                    b.HasKey("ScheduledDeliveryId");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("DestinationLocationId");

                    b.ToTable("ScheduledDelivery");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.UserLog", b =>
                {
                    b.Property<int>("UserLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InsertedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("InsertedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Serialized")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vUserId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(256)")
                        .HasComputedColumnSql("CONVERT([nvarchar](256),json_value([Serialized],N'$.UserId'))")
                        .HasMaxLength(256);

                    b.HasKey("UserLogId");

                    b.ToTable("UserLogs");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Area", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.AreaType", "AreaTypeReference")
                        .WithMany("Areas")
                        .HasForeignKey("AreaType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SVT.Platform.Data.Models.Pool", "Pool")
                        .WithMany("Areas")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.AreaDeliveryType", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.Area", "Area")
                        .WithMany("AreaDeliveryTypes")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SVT.Platform.Data.Models.DeliveryType", "DeliveryTypeReference")
                        .WithMany("AreaDeliveryTypes")
                        .HasForeignKey("DeliveryType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.AreaMap", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.Area", "NextArea")
                        .WithMany("PreviousAreas")
                        .HasForeignKey("NextAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SVT.Platform.Data.Models.Area", "PreviousArea")
                        .WithMany("NextAreas")
                        .HasForeignKey("PreviousAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.AreaOverflow", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.Area", "DestinationArea")
                        .WithMany("AreasOverflowFor")
                        .HasForeignKey("DestinationAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SVT.Platform.Data.Models.Area", "OverflowArea")
                        .WithMany("AreaOverflows")
                        .HasForeignKey("OverflowAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Delivery", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.DeliveryType", "DeliveryTypeReference")
                        .WithMany("Deliveries")
                        .HasForeignKey("DeliveryType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SVT.Platform.Data.Models.Area", "DestinationArea")
                        .WithMany("Deliveries")
                        .HasForeignKey("DestinationAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SVT.Platform.Data.Models.Delivery", "PreviousPrioritizedDelivery")
                        .WithOne("NextPrioritizedDelivery")
                        .HasForeignKey("SVT.Platform.Data.Models.Delivery", "PreviousPrioritizedDeliveryId");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Itinerary", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.Job", "Job")
                        .WithMany("Itineraries")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SVT.Platform.Data.Models.Location", "Location")
                        .WithMany("Itineraries")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Job", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.Delivery", "Delivery")
                        .WithMany("Jobs")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Location", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.Area", "Area")
                        .WithMany("Locations")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SVT.Platform.Data.Models.Delivery", "Delivery")
                        .WithMany("Locations")
                        .HasForeignKey("DeliveryId");

                    b.HasOne("SVT.Platform.Data.Models.LocationType", "LocationTypeReference")
                        .WithMany("Locations")
                        .HasForeignKey("LocationType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.ScheduledDelivery", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.Delivery", "Delivery")
                        .WithMany("ScheduledDeliveries")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SVT.Platform.Data.Models.Location", "DestinationLocation")
                        .WithMany("ScheduledDeliveries")
                        .HasForeignKey("DestinationLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
