// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.SqlServer.Types;
using SVT.Platform.Data;

namespace SVT.Platform.Data.Migrations
{
    [DbContext(typeof(SVTContext))]
    partial class SVTContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SVT.Platform.Data.Models.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AreaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("PoolId")
                        .HasColumnType("int");

                    b.HasKey("AreaId");

                    b.HasIndex("AreaType");

                    b.HasIndex("PoolId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.AreaDeliveryType", b =>
                {
                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryType")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("AreaId", "DeliveryType");

                    b.HasIndex("DeliveryType");

                    b.ToTable("AreaDeliveryTypes");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.AreaHierarchy", b =>
                {
                    b.Property<SqlHierarchyId>("Node")
                        .HasColumnType("hierarchyid");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<short?>("NodeLevel")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("smallint")
                        .HasComputedColumnSql("[Node].[GetLevel]()");

                    b.HasKey("Node");

                    b.HasIndex("AreaId");

                    b.ToTable("AreaHierarchy");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.AreaMap", b =>
                {
                    b.Property<int>("DestinationAreaId")
                        .HasColumnType("int");

                    b.Property<int>("SourceAreaId")
                        .HasColumnType("int");

                    b.HasKey("DestinationAreaId", "SourceAreaId");

                    b.HasIndex("SourceAreaId");

                    b.ToTable("AreaMaps");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.AreaType", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Value");

                    b.ToTable("AreaTypes");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Delivery", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Canceled")
                        .HasColumnType("datetime2");

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("Completed")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("DestinationAreaId")
                        .HasColumnType("int");

                    b.Property<string>("InsertedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("InsertedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("DeliveryId");

                    b.HasIndex("DeliveryType");

                    b.HasIndex("DestinationAreaId");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.DeliveryType", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Value");

                    b.ToTable("DeliveryTypes");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.DevLog", b =>
                {
                    b.Property<int>("DevLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InsertedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("InsertedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Serialized")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DevLogId");

                    b.ToTable("DevLogs");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Itinerary", b =>
                {
                    b.Property<int>("ItineraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AethonRunId")
                        .HasColumnType("int");

                    b.Property<string>("InsertedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("InsertedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ItineraryId");

                    b.HasIndex("JobId");

                    b.HasIndex("LocationId");

                    b.ToTable("Itineraries");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AethonJobId")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int");

                    b.Property<string>("InsertedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("InsertedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("JobId");

                    b.HasIndex("DeliveryId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("DeliveryId")
                        .HasColumnType("int");

                    b.Property<string>("InsertedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("InsertedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("Reserved")
                        .HasColumnType("bit");

                    b.HasKey("LocationId");

                    b.HasIndex("AreaId");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("LocationType");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.LocationType", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Value");

                    b.ToTable("LocationTypes");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Pool", b =>
                {
                    b.Property<int>("PoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("PoolId");

                    b.ToTable("Pools");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.UserLog", b =>
                {
                    b.Property<int>("UserLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InsertedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("InsertedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Serialized")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vUserId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(256)")
                        .HasComputedColumnSql("CONVERT([nvarchar](256),json_value([Serialized],N'$.UserId'))")
                        .HasMaxLength(256);

                    b.HasKey("UserLogId");

                    b.ToTable("UserLogs");
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Area", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.AreaType", "AreaTypeReference")
                        .WithMany("Areas")
                        .HasForeignKey("AreaType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SVT.Platform.Data.Models.Pool", "Pool")
                        .WithMany("Areas")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.AreaDeliveryType", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.Area", "Area")
                        .WithMany("AreaDeliveryTypes")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SVT.Platform.Data.Models.DeliveryType", "DeliveryTypeReference")
                        .WithMany("AreaDeliveryTypes")
                        .HasForeignKey("DeliveryType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.AreaHierarchy", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.Area", "Area")
                        .WithMany("AreaHierarchies")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.AreaMap", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.Area", "DestinationArea")
                        .WithMany("SourceAreas")
                        .HasForeignKey("DestinationAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SVT.Platform.Data.Models.Area", "SourceArea")
                        .WithMany("DestinationAreas")
                        .HasForeignKey("SourceAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Delivery", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.DeliveryType", "DeliveryTypeReference")
                        .WithMany("Deliveries")
                        .HasForeignKey("DeliveryType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SVT.Platform.Data.Models.Area", "DestinationArea")
                        .WithMany("Deliveries")
                        .HasForeignKey("DestinationAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Itinerary", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.Job", "Job")
                        .WithMany("Itineraries")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SVT.Platform.Data.Models.Location", "Location")
                        .WithMany("Itineraries")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Job", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.Delivery", "Delivery")
                        .WithMany("Jobs")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SVT.Platform.Data.Models.Location", b =>
                {
                    b.HasOne("SVT.Platform.Data.Models.Area", "Area")
                        .WithMany("Locations")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SVT.Platform.Data.Models.Delivery", "Delivery")
                        .WithMany("Locations")
                        .HasForeignKey("DeliveryId");

                    b.HasOne("SVT.Platform.Data.Models.LocationType", "LocationTypeReference")
                        .WithMany("Locations")
                        .HasForeignKey("LocationType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
